log-commands: true
log-chat: true
log-join: true
log-quit: true
log-kick: true
log-death: true
log-ip: true
log-disallowed-connections: true
use-old-logging: false
use-permissions: false
auto-update: true