name: SuperLogger
main: me.zack6849.logger.main
version: 1.3.8
author: zack6849
commands:
    sl:
        description: reloads superlogger 
        usage: /sl reload
permissions:
    superlogger.bypass.connection:
        description: permission to bypass connection logging
        default: false
    superlogger.bypass.chat:
        description: permission to bypass chat logging
        default: false
    superlogger.bypass.death:
        description: permission to bypass death logging
        default: false
    superlogger.bypass.command:
        description: permission to bypass command logging
        default: false
    superlogger.bypass.*:
        description: permission to bypass all logging
        children:
            superlogger.bypass.death: true
            superlogger.bypass.chat: true
            superlogger.bypass.connection: true
            superlogger.bypass.command: true